package com.lpan.study.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lpan.study.db.entity.Friend;
import com.lpan.study.db.entity.Student;

import com.lpan.study.greendao.FriendDao;
import com.lpan.study.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final FriendDao friendDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        friendDao = new FriendDao(friendDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(Friend.class, friendDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        friendDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
