package com.lpan.study.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lpan.study.db.entity.Student;
import com.lpan.study.db.entity.Friend;

import com.lpan.study.greendao.StudentDao;
import com.lpan.study.greendao.FriendDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig friendDaoConfig;

    private final StudentDao studentDao;
    private final FriendDao friendDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(Friend.class, friendDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        friendDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

}
